name: Build and Deploy to Azure Env 2
run-name: ${{ github.actor }} is testing my repo ${{github.repository }}. 🚀
on:
  push:
    branches: ['master']
  workflow_dispatch:

jobs:
  buildImage:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Azure Container Registry Login
        uses: Azure/docker-login@v1
        with:
          # Container registry username
          username: 'ccdemo0802'
          # Container registry password
          password: 'x7wRX/P3xd8/Cy5J5JeibKk2cAFcmVRsd+ey4JspI6+ACRBz+3hB'
          # Container registry server url
          login-server: 'ccdemo0802.azurecr.io'
      
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ccdemo0802.azurecr.io/hello-world-app:${{ github.sha }}
          file: ./Dockerfile

  deploytoAKS:
    runs-on: ubuntu-latest
    needs: [buildImage]
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        
      # Log in with your Azure credentials
      - name: 'Az CLI login'
        uses: azure/login@v1
        with:
          client-id: 'caf1b1e7-3e49-453e-967f-d442db52e447'
          tenant-id: 'd3275226-ed38-4275-aa8c-883c16f01d9e'
          subscription-id: '98a3196f-6832-4fbc-b17d-84d0c75b73ab'
      
      - name: Setup kubelogin
        uses: Azure/use-kubelogin@v1
    
      - name: Azure Kubernetes set context
        uses: Azure/aks-set-context@v3
        with:
          # Resource Group Name
          resource-group: 'github-action-rg'
          # AKS Cluster Name
          cluster-name: 'ccdemo0802'
          # AKS Cluster Subscription
          subscription: '98a3196f-6832-4fbc-b17d-84d0c75b73ab'
          # Get cluster admin credentials. Values: true or false
          admin: 'false'
          # Enables kubelogin for non-admin user scenario. Values: true or false
          use-kubelogin: 'true'
        
      # Deploys application based on given manifest file
      - name: Deploys application
        uses: Azure/k8s-deploy@v4
        with:
          action: deploy
          manifests: |
            kubernetes/hello-world-deployment.yaml
            kubernetes/hello-world-service.yaml
          images: |
            ccdemo0802.azurecr.io/hello-world-app:${{ github.sha }}
